"use client";

import { useState } from "react";
import useSWR from "swr";
import { apiFetcher } from "@/lib/api/fetcher";

interface MetricSummary {
  metricName: string;
  staffCount: number;
  avgTarget: number;
  avgAchieved: number;
  metCount: number;
  unmetCount: number;
  achievementPct: number;
}

interface StaffMetric {
  metricName: string;
  target: number;
  achieved: number;
  met: boolean;
}

interface StaffKpi {
  staffId: string;
  staffName: string;
  subTeam: string | null;
  roleCode: string;
  metrics: StaffMetric[];
  oi: { registered: number; won: number } | null;
  overallPct: number;
}

interface KpiData {
  period: string;
  overallAchievement: number;
  totalStaff: number;
  totalMetrics: number;
  totalMet: number;
  metricSummaries: MetricSummary[];
  staffKpis: StaffKpi[];
}

const ROLE_COLORS: Record<string, string> = {
  HOD: "bg-purple-100 text-purple-700",
  SM: "bg-blue-100 text-blue-700",
  TL: "bg-green-100 text-green-700",
  TM: "bg-gray-100 text-gray-700",
  BIM_TL: "bg-teal-100 text-teal-700",
  BIM_MOD: "bg-cyan-100 text-cyan-700",
};

function KpiCard({ label, value, sub, color = "text-gray-900" }: {
  label: string; value: string | number; sub?: string; color?: string;
}) {
  return (
    <div className="bg-white rounded-lg border border-gray-200 p-4">
      <p className="text-xs font-medium text-gray-500 uppercase tracking-wide">{label}</p>
      <p className={`mt-1 text-2xl font-bold ${color}`}>{value}</p>
      {sub && <p className="mt-0.5 text-xs text-gray-500">{sub}</p>}
    </div>
  );
}

function ProgressRing({ pct, size = 56 }: { pct: number; size?: number }) {
  const radius = (size - 8) / 2;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (Math.min(pct, 100) / 100) * circumference;
  const color = pct >= 100 ? "text-green-500" : pct >= 70 ? "text-yellow-500" : "text-red-500";

  return (
    <div className="relative inline-flex items-center justify-center" style={{ width: size, height: size }}>
      <svg width={size} height={size} className="-rotate-90">
        <circle cx={size / 2} cy={size / 2} r={radius} fill="none" stroke="#e5e7eb" strokeWidth={4} />
        <circle
          cx={size / 2} cy={size / 2} r={radius} fill="none"
          stroke="currentColor" strokeWidth={4} strokeLinecap="round"
          strokeDasharray={circumference} strokeDashoffset={offset}
          className={color}
        />
      </svg>
      <span className="absolute text-xs font-bold text-gray-700">{pct}%</span>
    </div>
  );
}

function generatePeriodOptions(): string[] {
  const now = new Date();
  const periods: string[] = [];
  for (let i = 0; i < 8; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i * 3, 1);
    const q = Math.ceil((d.getMonth() + 1) / 3);
    periods.push(`${d.getFullYear()}-Q${q}`);
  }
  return [...new Set(periods)];
}

export default function KpiDashboardPage() {
  const periods = generatePeriodOptions();
  const [period, setPeriod] = useState(periods[0]);

  const { data, error, isLoading } = useSWR<KpiData>(
    `/api/kpi?period=${period}`,
    apiFetcher
  );

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="h-6 w-6 animate-spin rounded-full border-2 border-primary-500 border-t-transparent" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
        Failed to load KPI data
      </div>
    );
  }

  if (!data) return null;

  const hasData = data.totalStaff > 0;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-gray-800">KPI Dashboard</h1>
          <p className="text-sm text-gray-500">Performance scorecard and achievement tracking</p>
        </div>
        <select
          value={period}
          onChange={(e) => setPeriod(e.target.value)}
          className="rounded-lg border border-gray-200 px-3 py-2 text-sm bg-white"
        >
          {periods.map((p) => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>
      </div>

      {!hasData ? (
        <div className="bg-white rounded-lg border border-gray-200 p-12 text-center">
          <p className="text-gray-400 text-sm">
            No KPI data available for {period}.
          </p>
          <p className="text-gray-400 text-xs mt-2">
            KPI calculations are generated by the compute worker. Once configured, metrics will appear here automatically.
          </p>
        </div>
      ) : (
        <>
          {/* Overview KPIs */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <KpiCard
              label="Overall Achievement"
              value={`${data.overallAchievement}%`}
              color={data.overallAchievement >= 80 ? "text-green-600" : data.overallAchievement >= 60 ? "text-yellow-600" : "text-red-600"}
            />
            <KpiCard label="Staff Tracked" value={data.totalStaff} />
            <KpiCard label="Metrics Met" value={data.totalMet} sub={`of ${data.totalMetrics} total`} />
            <KpiCard
              label="Miss Rate"
              value={`${data.totalMetrics > 0 ? Math.round(((data.totalMetrics - data.totalMet) / data.totalMetrics) * 100) : 0}%`}
              color={data.totalMetrics - data.totalMet > 0 ? "text-red-600" : "text-green-600"}
            />
          </div>

          {/* Metric Summaries */}
          {data.metricSummaries.length > 0 && (
            <div className="bg-white rounded-lg border border-gray-200 p-5">
              <h3 className="text-sm font-semibold text-gray-800 mb-4">Metric Achievement Summary</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {data.metricSummaries.map((m) => (
                  <div key={m.metricName} className="rounded-lg border border-gray-100 p-4">
                    <div className="flex items-center justify-between">
                      <p className="text-sm font-medium text-gray-800">{m.metricName}</p>
                      <ProgressRing pct={m.achievementPct} size={44} />
                    </div>
                    <div className="mt-2 flex gap-4 text-xs text-gray-500">
                      <span>Avg Target: {m.avgTarget.toFixed(1)}</span>
                      <span>Avg Achieved: {m.avgAchieved.toFixed(1)}</span>
                    </div>
                    <div className="mt-2 flex gap-2">
                      <span className="rounded bg-green-50 px-2 py-0.5 text-xs text-green-700">
                        {m.metCount} met
                      </span>
                      {m.unmetCount > 0 && (
                        <span className="rounded bg-red-50 px-2 py-0.5 text-xs text-red-700">
                          {m.unmetCount} unmet
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Staff KPI Table */}
          <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
            <div className="px-5 py-3 border-b border-gray-200 bg-gray-50">
              <h3 className="text-sm font-semibold text-gray-700">Individual Scorecards</h3>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-100 text-left text-xs text-gray-400">
                    <th className="px-5 py-2">Staff</th>
                    <th className="px-3 py-2">Role</th>
                    <th className="px-3 py-2">Pod</th>
                    <th className="px-3 py-2 text-center">Overall</th>
                    <th className="px-3 py-2 text-center">Metrics</th>
                    <th className="px-3 py-2 text-center">OI Registered</th>
                    <th className="px-3 py-2 text-center">OI Won</th>
                  </tr>
                </thead>
                <tbody>
                  {data.staffKpis.map((s) => {
                    const metCount = s.metrics.filter((m) => m.met).length;
                    return (
                      <tr key={s.staffId} className="border-b border-gray-50 hover:bg-gray-50">
                        <td className="px-5 py-3 font-medium text-gray-800">{s.staffName}</td>
                        <td className="px-3 py-3">
                          <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${ROLE_COLORS[s.roleCode] ?? "bg-gray-100 text-gray-700"}`}>
                            {s.roleCode}
                          </span>
                        </td>
                        <td className="px-3 py-3 text-gray-500">{s.subTeam ?? "—"}</td>
                        <td className="px-3 py-3 text-center">
                          <ProgressRing pct={s.overallPct} size={40} />
                        </td>
                        <td className="px-3 py-3 text-center">
                          <span className="text-green-600 font-medium">{metCount}</span>
                          <span className="text-gray-400"> / {s.metrics.length}</span>
                        </td>
                        <td className="px-3 py-3 text-center text-gray-700">
                          {s.oi ? s.oi.registered : "—"}
                        </td>
                        <td className="px-3 py-3 text-center text-gray-700">
                          {s.oi ? s.oi.won : "—"}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Expandable detail — show individual metrics for each staff */}
          {data.staffKpis.filter((s) => s.metrics.length > 0).map((s) => (
            <details key={s.staffId} className="bg-white rounded-lg border border-gray-200 overflow-hidden">
              <summary className="px-5 py-3 cursor-pointer hover:bg-gray-50 text-sm font-medium text-gray-700">
                {s.staffName} — Detailed Metrics ({s.metrics.length})
              </summary>
              <div className="px-5 py-3 border-t border-gray-100">
                <div className="space-y-2">
                  {s.metrics.map((m) => {
                    const pct = m.target > 0 ? Math.round((m.achieved / m.target) * 100) : 0;
                    return (
                      <div key={m.metricName} className="flex items-center gap-3">
                        <span className="w-48 text-xs text-gray-600 shrink-0 truncate">{m.metricName}</span>
                        <div className="flex-1 h-2 rounded-full bg-gray-100">
                          <div
                            className={`h-2 rounded-full ${m.met ? "bg-green-500" : "bg-red-400"}`}
                            style={{ width: `${Math.min(pct, 100)}%` }}
                          />
                        </div>
                        <span className="text-xs text-gray-500 w-24 text-right shrink-0">
                          {m.achieved.toFixed(1)} / {m.target.toFixed(1)}
                        </span>
                        <span className={`text-xs font-bold w-10 text-right ${m.met ? "text-green-600" : "text-red-600"}`}>
                          {pct}%
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </details>
          ))}
        </>
      )}
    </div>
  );
}
