-- ════════════════════════════════════════════════════════════════════════════
-- Migration 004: External Work Order & Tender
-- Reference: Database Design Specification v1.0 §3
-- Tables: EXTERNAL_WO, TENDER
-- Depends on: DEPARTMENT, STAFF (migrations 002–003)
-- ════════════════════════════════════════════════════════════════════════════

-- ── EXTERNAL_WO ─────────────────────────────────────────────────────────────
-- DB Spec §3: "The corporate-system reference record; system of record for
-- external intake." This table is seed data mirrored from the corporate
-- Work Order/EWM system (SAD §11, Phase 4 integration); in Phase 1–3 it is
-- populated manually at WO creation time (PRD FR-01).
CREATE TABLE EXTERNAL_WO (
    Id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ExtWO_No        VARCHAR(30) NOT NULL,
    ProjectCode     VARCHAR(30),
    SourceDeptId    UUID NOT NULL REFERENCES DEPARTMENT(Id) ON DELETE RESTRICT,
    EndUser         VARCHAR(150),
    ReceivedDate    DATE NOT NULL,
    Status          VARCHAR(20) NOT NULL DEFAULT 'Open',
    CreatedAt       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UpdatedAt       TIMESTAMPTZ,
    CONSTRAINT uq_externalwo_extwono UNIQUE (ExtWO_No)
);
COMMENT ON TABLE EXTERNAL_WO IS 'PRD §11 — external corporate WO reference; seed record for CSI_WO (FR-01)';
CREATE INDEX idx_externalwo_sourcedept ON EXTERNAL_WO(SourceDeptId);

-- ── TENDER ──────────────────────────────────────────────────────────────────
-- DB Spec §3: "The v1.1 top-level business object (PRD §4.3). Sits above
-- CSI_WO in the Tender → WO → Task → Effort hierarchy."
CREATE TABLE TENDER (
    Id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    TenderNo        VARCHAR(30) NOT NULL,
    TenderName      VARCHAR(200) NOT NULL,
    Client          VARCHAR(150) NOT NULL,
    TenderCategory  VARCHAR(50),
    ClosingDate     DATE NOT NULL,
    EstimatedValue  NUMERIC(15,2) NOT NULL,
    SubmittedValue  NUMERIC(15,2),
    WinValue        NUMERIC(15,2),
    Status          VARCHAR(20) NOT NULL DEFAULT 'Prospect',
    TenderOwnerId   UUID NOT NULL REFERENCES STAFF(Id) ON DELETE RESTRICT,
    CreatedAt       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UpdatedAt       TIMESTAMPTZ,
    CONSTRAINT uq_tender_tenderno UNIQUE (TenderNo),
    CONSTRAINT chk_tender_status CHECK (Status IN
        ('Prospect','Qualified','InProgress','Submitted','Clarification','Won','Lost','Cancelled')),
    CONSTRAINT chk_tender_estimatedvalue CHECK (EstimatedValue > 0),
    CONSTRAINT chk_tender_submittedvalue CHECK (SubmittedValue IS NULL OR SubmittedValue >= 0),
    -- FR-58 / Wireframe Spec Screen 4: WinValue only meaningful once Status = Won;
    -- enforced at the application layer (PATCH /api/tender/:id, API Spec §6) rather
    -- than a CHECK constraint, since the constraint would need to evaluate against
    -- the value at the moment Status transitions, which a stateless CHECK cannot do.
    CONSTRAINT chk_tender_winvalue CHECK (WinValue IS NULL OR WinValue >= 0)
);
COMMENT ON TABLE TENDER IS 'PRD §4.3, §11 — v1.1 top-level business object; Tender → WO → Task → Effort hierarchy (FR-57)';
COMMENT ON COLUMN TENDER.TenderNo IS 'Auto-generated by the application layer at creation; never entered manually (FR-57, API Spec POST /api/tender validation)';

CREATE INDEX idx_tender_status_closing ON TENDER(Status, ClosingDate);
CREATE INDEX idx_tender_owner ON TENDER(TenderOwnerId);
